# Generated by Django 2.1.7 on 2019-12-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('order', 'updated')},
        ),
        migrations.AlterField(
            model_name='card',
            name='order',
            field=models.FloatField(default=0),
        ),
    ]
