# Generated by Django 3.0.1 on 2020-03-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0005_delete_milestonecard'),
        ('card', '0002_auto_20191223_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='milestone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='milestone.Milestone'),
        ),
    ]
