# Generated by Django 3.0.1 on 2020-03-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_card_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='points_estimate',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
