# Generated by Django 3.0.1 on 2020-03-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20200326_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='points',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='points_estimate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
