# Generated by Django 3.0.3 on 2020-03-28 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20200326_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='epic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.Card'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_epic',
            field=models.BooleanField(default=False),
        ),
    ]
