# Generated by Django 3.0.1 on 2020-03-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20191223_1832'),
        ('milestone', '0003_milestonecard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='milestonecard',
            unique_together={('milestone', 'card')},
        ),
    ]
