# Generated by Django 3.0.1 on 2020-03-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0004_auto_20200326_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MilestoneCard',
        ),
    ]
