# Generated by Django 2.1.7 on 2019-12-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='column',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
