# Generated by Django 2.1.7 on 2019-12-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectlabel',
            name='for_object',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
