# Generated by Django 2.1.7 on 2019-12-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_auto_20191223_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObjectLabel',
            new_name='LabelObject',
        ),
        migrations.AlterModelOptions(
            name='labelobject',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
