# Generated by Django 3.0.1 on 2019-12-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_auto_20191229_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labelobject',
            options={},
        ),
        migrations.RenameField(
            model_name='labelobject',
            old_name='for_type',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='labelobject',
            old_name='for_object',
            new_name='to',
        ),
        migrations.AlterUniqueTogether(
            name='labelobject',
            unique_together={('label', 'kind', 'to')},
        ),
    ]
