# Generated by Django 3.0.1 on 2019-12-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_auto_20191229_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
